#include "AccountMerge.h"

#include <windows.h>
#include <cstring>
#include <cstdio>
#include <string>
#include <vector>

// Cross-account character data sharing for Guda addon.
// On game startup, merges character data from all WoW accounts'
// SavedVariables into a single Lua file that the addon loads via .toc.

static std::string ReadFile(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) return "";
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0) { fclose(f); return ""; }
    std::string buf(size, '\0');
    fread(&buf[0], 1, size, f);
    fclose(f);
    return buf;
}

// Find the characters table block: ["characters"] = { ... }
// Returns the INNER content (between the outermost braces)
static std::string ExtractCharactersBlock(const std::string& content) {
    const char* needle = "[\"characters\"]";
    size_t pos = content.find(needle);
    if (pos == std::string::npos) return "";

    size_t braceStart = content.find('{', pos);
    if (braceStart == std::string::npos) return "";

    int depth = 1;
    size_t i = braceStart + 1;
    while (i < content.size() && depth > 0) {
        if (content[i] == '{') depth++;
        else if (content[i] == '}') depth--;
        i++;
    }
    if (depth != 0) return "";

    return content.substr(braceStart + 1, i - braceStart - 2);
}

// Inject ["account"] = "ACCTNAME" into each top-level character entry.
// Only matches ["key"] = { ... } at brace depth 0 within the block.
static std::string InjectAccountField(const std::string& block, const std::string& accountName) {
    std::string result;
    result.reserve(block.size() + accountName.size() * 20);

    int depth = 0;
    size_t entryStart = std::string::npos;
    size_t i = 0;

    while (i < block.size()) {
        if (block[i] == '{') {
            depth++;
            if (depth == 1) {
                // Opening brace of a top-level entry - remember position
                entryStart = i;
            }
            result += block[i];
            i++;
        } else if (block[i] == '}') {
            depth--;
            if (depth == 0 && entryStart != std::string::npos) {
                // Closing brace of a top-level entry - inject account field before it
                result += "\t\t\t[\"account\"] = \"" + accountName + "\",\n\t\t";
                entryStart = std::string::npos;
            }
            result += block[i];
            i++;
        } else {
            result += block[i];
            i++;
        }
    }

    return result;
}

void AccountMerge::Run() {
    // Skip if Guda addon is not installed
    DWORD attr = GetFileAttributesA("Interface\\AddOns\\Guda");
    if (attr == INVALID_FILE_ATTRIBUTES || !(attr & FILE_ATTRIBUTE_DIRECTORY)) return;

    WIN32_FIND_DATAA findData;
    HANDLE hFind = FindFirstFileA("WTF\\Account\\*", &findData);
    if (hFind == INVALID_HANDLE_VALUE) return;

    struct AccountData {
        std::string name;
        std::string charBlock;
    };
    std::vector<AccountData> accounts;

    do {
        if (!(findData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) continue;
        if (strcmp(findData.cFileName, ".") == 0 || strcmp(findData.cFileName, "..") == 0) continue;

        std::string accountName = findData.cFileName;
        std::string path = "WTF\\Account\\" + accountName + "\\SavedVariables\\Guda.lua";

        std::string content = ReadFile(path.c_str());
        if (content.empty()) continue;

        std::string charBlock = ExtractCharactersBlock(content);
        if (charBlock.empty()) continue;

        accounts.push_back({accountName, charBlock});
    } while (FindNextFileA(hFind, &findData));

    FindClose(hFind);

    if (accounts.size() <= 1) {
        FILE* out = fopen("Interface\\AddOns\\Guda\\GudaShared.lua", "w");
        if (out) {
            fprintf(out, "Guda_SharedCharacters = nil\n");
            fclose(out);
        }
        return;
    }

    FILE* out = fopen("Interface\\AddOns\\Guda\\GudaShared.lua", "w");
    if (!out) return;

    fprintf(out, "-- Generated by GudaIO DLL\n");
    fprintf(out, "Guda_SharedCharacters = {\n");

    for (auto& acct : accounts) {
        std::string tagged = InjectAccountField(acct.charBlock, acct.name);
        fprintf(out, "%s", tagged.c_str());
    }

    fprintf(out, "}\n");
    fclose(out);
}
